{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPl/yYpxBUDR8X9FAZ+18T8",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/ajitrathore/screener/blob/main/Scanner-app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 23,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "EroogIMRDncX",
        "outputId": "080edf3b-516b-4d0e-c7f0-b89e0a7097bb"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)\n",
            "Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.2)\n",
            "Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)\n",
            "Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)\n",
            "Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)\n",
            "Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.1)\n",
            "Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)\n",
            "Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)\n",
            "Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.3)\n",
            "Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)\n",
            "Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)\n",
            "Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)\n",
            "Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)\n",
            "Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)\n",
            "Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)\n",
            "Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.11.12)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)\n"
          ]
        }
      ],
      "source": [
        "!pip install yfinance pandas lxml"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import yfinance as yf\n",
        "import pandas as pd\n",
        "import requests\n",
        "from tqdm import tqdm\n",
        "import warnings\n",
        "import logging\n",
        "\n",
        "# 1. Setup: Silence warnings and yfinance logs\n",
        "warnings.filterwarnings(\"ignore\", category=FutureWarning)\n",
        "logging.getLogger('yfinance').setLevel(logging.CRITICAL)\n",
        "\n",
        "def get_sp500_tickers():\n",
        "    \"\"\"Fetches and cleans S&P 500 tickers from Wikipedia.\"\"\"\n",
        "    url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'\n",
        "    headers = {'User-Agent': 'Mozilla/5.0'}\n",
        "\n",
        "    try:\n",
        "        response = requests.get(url, headers=headers)\n",
        "        # Force pandas to read the first table\n",
        "        df = pd.read_html(response.text)[0]\n",
        "\n",
        "        # Take the first column, convert to string\n",
        "        raw_list = df.iloc[:, 0].astype(str).tolist()\n",
        "\n",
        "        clean_tickers = []\n",
        "        for t in raw_list:\n",
        "            t = t.strip().upper().replace('.', '-')\n",
        "            # Filter: must have letters, no '---', and reasonable length\n",
        "            if t.isalpha() or ('-' in t and t.replace('-', '').isalpha()):\n",
        "                if len(t) < 7 and t != 'SYMBOL':\n",
        "                    clean_tickers.append(t)\n",
        "\n",
        "        print(f\"✅ Successfully fetched {len(clean_tickers)} tickers.\")\n",
        "        print(f\"📌 Sample: {clean_tickers[:10]}\")\n",
        "        return clean_tickers\n",
        "    except Exception as e:\n",
        "        print(f\"❌ Error fetching tickers: {e}\")\n",
        "        return []\n",
        "\n",
        "def run_scanner():\n",
        "    tickers = get_sp500_tickers()\n",
        "    if not tickers:\n",
        "        return pd.DataFrame()\n",
        "\n",
        "    bullish_stocks = []\n",
        "    print(f\"\\nScanning stocks for Price > Prev Day IB High AND Price > Today ON High...\")\n",
        "\n",
        "    for ticker in tqdm(tickers):\n",
        "        try:\n",
        "            # Download 3 days to ensure we have 'Yesterday' and 'Today'\n",
        "            data = yf.download(ticker, period=\"3d\", interval=\"5m\", prepost=True, progress=False, auto_adjust=True)\n",
        "\n",
        "            if data.empty or len(data) < 20:\n",
        "                continue\n",
        "\n",
        "            # Flatten Multi-index columns if they exist\n",
        "            if isinstance(data.columns, pd.MultiIndex):\n",
        "                data.columns = data.columns.get_level_values(0)\n",
        "\n",
        "            # Convert to Chicago Time\n",
        "            data.index = data.index.tz_convert('America/Chicago')\n",
        "\n",
        "            # Identify the unique trading days\n",
        "            days = sorted(data.index.normalize().unique())\n",
        "            if len(days) < 2:\n",
        "                continue\n",
        "\n",
        "            yesterday = days[-2] # Previous trading day\n",
        "            today = days[-1]     # Current trading day\n",
        "\n",
        "            # --- LOGIC 1: PREVIOUS DAY INITIAL BALANCE HIGH (08:30 - 09:30 CT) ---\n",
        "            prev_day_data = data.loc[yesterday.strftime('%Y-%m-%d')]\n",
        "            ib_data = prev_day_data.between_time('08:30', '09:30')\n",
        "            if ib_data.empty: continue\n",
        "            prev_ib_high = ib_data['High'].max()\n",
        "\n",
        "            # --- LOGIC 2: TODAY'S OVERNIGHT HIGH (00:00 - 08:30 CT) ---\n",
        "            today_data = data.loc[today.strftime('%Y-%m-%d')]\n",
        "            on_data = today_data.between_time('00:00', '08:30')\n",
        "            if on_data.empty: continue\n",
        "            on_high = on_data['High'].max()\n",
        "\n",
        "            # --- LOGIC 3: CURRENT PRICE ---\n",
        "            current_price = today_data['Close'].iloc[-1]\n",
        "            on_high = today_data.between_time('00:00', '08:30')['High'].max()\n",
        "            # --- FINAL FILTER ---\n",
        "            if current_price > prev_ib_high and current_price > on_high:\n",
        "                bullish_stocks.append({\n",
        "                    \"Ticker\": ticker,\n",
        "                    \"Pivot Price\":on_high,\n",
        "                    \"Gap_Up_%\": round(((float(current_price) / float(prev_ib_high)) - 1) * 100, 2)\n",
        "                })\n",
        "\n",
        "        except Exception:\n",
        "            continue\n",
        "\n",
        "    return pd.DataFrame(bullish_stocks)\n",
        "\n",
        "# EXECUTE SCRIPT\n",
        "results_df = run_scanner()\n",
        "\n",
        "if not results_df.empty:\n",
        "    print(\"\\n🚀 BULLISH BREAKOUTS FOUND:\")\n",
        "    # Sort by the ones showing most strength (highest Gap Up %)\n",
        "    display(results_df.sort_values(by=\"Gap_Up_%\", ascending=False))\n",
        "else:\n",
        "    print(\"\\n😴 No stocks currently meet the breakout criteria.\")\n",
        "\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 545
        },
        "id": "BDbkXgv2Douc",
        "outputId": "cde3f43d-cc12-4f2a-bb20-0d1da7f2d39d"
      },
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ Successfully fetched 503 tickers.\n",
            "📌 Sample: ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A']\n",
            "\n",
            "Scanning stocks for Price > Prev Day IB High AND Price > Today ON High...\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "100%|██████████| 503/503 [00:56<00:00,  8.87it/s]"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "🚀 BULLISH BREAKOUTS FOUND:\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   Ticker  Pivot Price  Prev_IB_High  Gap_Up_%\n",
              "14   BLDR   119.065002        109.67     13.21\n",
              "54    LEN   115.750000        107.25     10.01\n",
              "77    PHM   129.880005        121.00      9.05\n",
              "30    DHI   153.000000        143.23      8.95\n",
              "53   LRCX   208.200000        202.41      7.87\n",
              "..    ...          ...           ...       ...\n",
              "0       A   148.330000        148.74      0.41\n",
              "12     BA   230.639999        233.11      0.36\n",
              "15   CHRW   168.389999        168.32      0.32\n",
              "57    LMT   535.630500        542.87      0.22\n",
              "63     MU   333.790000        342.33      0.18\n",
              "\n",
              "[103 rows x 4 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-95f8c951-d7ce-4f6a-aed5-deb7b476aeee\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Ticker</th>\n",
              "      <th>Pivot Price</th>\n",
              "      <th>Prev_IB_High</th>\n",
              "      <th>Gap_Up_%</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>14</th>\n",
              "      <td>BLDR</td>\n",
              "      <td>119.065002</td>\n",
              "      <td>109.67</td>\n",
              "      <td>13.21</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>54</th>\n",
              "      <td>LEN</td>\n",
              "      <td>115.750000</td>\n",
              "      <td>107.25</td>\n",
              "      <td>10.01</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>77</th>\n",
              "      <td>PHM</td>\n",
              "      <td>129.880005</td>\n",
              "      <td>121.00</td>\n",
              "      <td>9.05</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>30</th>\n",
              "      <td>DHI</td>\n",
              "      <td>153.000000</td>\n",
              "      <td>143.23</td>\n",
              "      <td>8.95</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>53</th>\n",
              "      <td>LRCX</td>\n",
              "      <td>208.200000</td>\n",
              "      <td>202.41</td>\n",
              "      <td>7.87</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>A</td>\n",
              "      <td>148.330000</td>\n",
              "      <td>148.74</td>\n",
              "      <td>0.41</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>12</th>\n",
              "      <td>BA</td>\n",
              "      <td>230.639999</td>\n",
              "      <td>233.11</td>\n",
              "      <td>0.36</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>15</th>\n",
              "      <td>CHRW</td>\n",
              "      <td>168.389999</td>\n",
              "      <td>168.32</td>\n",
              "      <td>0.32</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>57</th>\n",
              "      <td>LMT</td>\n",
              "      <td>535.630500</td>\n",
              "      <td>542.87</td>\n",
              "      <td>0.22</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>63</th>\n",
              "      <td>MU</td>\n",
              "      <td>333.790000</td>\n",
              "      <td>342.33</td>\n",
              "      <td>0.18</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>103 rows × 4 columns</p>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-95f8c951-d7ce-4f6a-aed5-deb7b476aeee')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-95f8c951-d7ce-4f6a-aed5-deb7b476aeee button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-95f8c951-d7ce-4f6a-aed5-deb7b476aeee');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    <div id=\"df-24781c27-0c7e-4b6c-a1ad-f9979b7d5e71\">\n",
              "      <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-24781c27-0c7e-4b6c-a1ad-f9979b7d5e71')\"\n",
              "                title=\"Suggest charts\"\n",
              "                style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "      </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "      <script>\n",
              "        async function quickchart(key) {\n",
              "          const quickchartButtonEl =\n",
              "            document.querySelector('#' + key + ' button');\n",
              "          quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "          quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "          try {\n",
              "            const charts = await google.colab.kernel.invokeFunction(\n",
              "                'suggestCharts', [key], {});\n",
              "          } catch (error) {\n",
              "            console.error('Error during call to suggestCharts:', error);\n",
              "          }\n",
              "          quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "          quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "        }\n",
              "        (() => {\n",
              "          let quickchartButtonEl =\n",
              "            document.querySelector('#df-24781c27-0c7e-4b6c-a1ad-f9979b7d5e71 button');\n",
              "          quickchartButtonEl.style.display =\n",
              "            google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "        })();\n",
              "      </script>\n",
              "    </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"    print(\\\"\\\\n\\ud83d\\ude34 No stocks currently meet the breakout criteria\",\n  \"rows\": 103,\n  \"fields\": [\n    {\n      \"column\": \"Ticker\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 103,\n        \"samples\": [\n          \"SW\",\n          \"WAB\",\n          \"ROL\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Pivot Price\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 768.5467572762793,\n        \"min\": 16.780000686645508,\n        \"max\": 7500.0,\n        \"num_unique_values\": 102,\n        \"samples\": [\n          42.27,\n          225.0,\n          60.435001373291016\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Prev_IB_High\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 750.9108114021404,\n        \"min\": 16.38,\n        \"max\": 7315.5,\n        \"num_unique_values\": 103,\n        \"samples\": [\n          41.42,\n          222.0,\n          60.13\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Gap_Up_%\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2.2640079801137305,\n        \"min\": 0.18,\n        \"max\": 13.21,\n        \"num_unique_values\": 93,\n        \"samples\": [\n          2.64,\n          3.5,\n          1.93\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "    # WRITE TO GOOGLE SHEETS\n",
        "try:\n",
        "        sh = gc.open('StockScanner') # Must match your Sheet name exactly\n",
        "        worksheet = sh.get_worksheet(0)\n",
        "        worksheet.clear()\n",
        "        worksheet.update([results_df.columns.values.tolist()] + results_df.values.tolist())\n",
        "        print(f\"\\n✅ Success! Top 15 stocks sent to your 'StockScanner' Sheet.\")\n",
        "except Exception as e:\n",
        "        print(f\"\\n❌ Sheet Error: Make sure you have a sheet named 'StockScanner' in your Drive.\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "BIm7-BvgM7Bh",
        "outputId": "062ee936-6f93-4ba8-c61e-558601977b09"
      },
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "✅ Success! Top 15 stocks sent to your 'StockScanner' Sheet.\n"
          ]
        }
      ]
    }
  ]
}